# Misc settings
ignore-path-in-watch-later-config
save-position-on-quit
no-osd-bar
osc=no
keep-open=yes
autofit=90%x90%
resume-playback=yes
hr-seek = yes
watch-later-dir=~/Sync/Misc/mpv-watch-later
osd-font="SFProDisplay-Medium"
sub-font="SFProDisplay-Medium"
sub-outline-siz=1
sub-outline-color=#808080FF

# Hardware & Quality Settings
vo=gpu-next,gpu
hwdec=auto
gpu-api=auto 
hwdec-codecs=all 
target-colorspace-hint=no 

# Screenshot settings 
screenshot-format=png
screenshot-dir=~/Downloads/
screenshot-template="%F %p"

