keys:
  - &host_NixOS-MBP age1dvlkxhqkh2w06qhxa44n908tyl92dyu3vj9kkljtrum2ctvwv9cqxfzy9q
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *host_NixOS-MBP

  - path_regex: praw.ini$
    key_groups:
    - age:
      - *host_NixOS-MBP

  - path_regex: gallery-dl/config\.json
    key_groups:
    - age:
      - *host_NixOS-MBP

  - path_regex: gh/hosts\.yml
    key_groups:
    - age:
      - *host_NixOS-MBP
