# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  inputs,
  ...
}:

{
  nixpkgs.overlays = [ inputs.rust-overlay.overlays.default ];
  environment.systemPackages = with pkgs; [
    # Apps
    kitty
    neovide
    neovim
    tree-sitter
    fish
    qbittorrent
    megabasterd
    ruffle
    whisper-cpp
    vscode
    diff-so-fancy
    delta
    dolphin-emu
    copyparty-most

    lazygit

    wordnet

    # Command Line Tools / CLIs
    uutils-coreutils-noprefix
    coreutils-prefixed
    gnumake
    fd
    fzf
    eza
    gcc
    cmake
    bat
    zoxide
    ripgrep
    starship
    bottom
    yazi
    sd
    ffmpeg-full
    pkg-config
    lnav
    jujutsu
    yt-dlp
    gallery-dl
    exiftool
    unrar
    imagemagick
    tesseract
    socat
    age
    sops
    yq-go
    jnv
    jq
    p7zip
    whois
    git-filter-repo
    tig
    atuin
    pastel
    wget
    chezmoi
    rclone
    watchexec
    dua
    gifski

    # Language Packages
    # Misc languages
    pkgs.rust-bin.stable.latest.default
    rust-analyzer
    markdown-oxide
    nixfmt
    nixd
    hyprls
    uv
    # Golang
    go
    gopls
    # Lua
    stylua
    lua-language-server
    # JS
    biome
    yarn
    nodejs

    # Misc Packages
    nerd-fonts.iosevka
    dconf
  ];

  programs.fish.enable = true;

  nix = {
    settings.experimental-features = [
      "nix-command"
      "flakes"
    ];
    optimise.automatic = true;
    gc = {
      options = "--delete-older-than 7d";
      automatic = true;
    };
  };

  nixpkgs.config.allowUnfree = true;
}
