# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  inputs,
  ...
}:

{
  environment.systemPackages = with pkgs; [
    # Apps
    kitty
    neovide
    neovim
    fish
    activitywatch
    qview
    qbittorrent
    megabasterd
    ruffle
    whisper-cpp
    (mpv-unwrapped.override {
      ffmpeg = ffmpeg-full;
    })
    vscode
    diff-so-fancy
    delta

    dolphin-emu
    libreoffice

    # AI Tools
    code-cursor-fhs

    # Git tools
    github-desktop
    lazygit

    # Command Line Tools / CLIs
    uutils-coreutils-noprefix
    coreutils-prefixed
    gnumake
    fd
    fzf
    eza
    gcc
    cmake
    bat
    zoxide
    ripgrep
    starship
    bottom
    yazi
    sd
    (ffmpeg-full.override {
      withUnfree = true;
    })
    pkg-config
    slurp
    lnav
    wl-clipboard
    jujutsu
    yt-dlp
    gallery-dl
    exiftool
    unrar
    imagemagick
    tesseract
    socat
    age
    sops
    git-crypt
    yq-go
    snapper
    jnv
    jq
    p7zip
    whois
    git-filter-repo
    tig
    atuin
    pastel
    wget
    chezmoi

    # Command Line Apps / CLI Apps
    dua

    # LSPs, Linters, and language Related Packages
    # Misc languages
    rust-analyzer
    markdown-oxide
    nixfmt
    nixd
    hyprls
    uv
    # Golang
    go
    gopls
    # Lua
    stylua
    lua-language-server
    # JS
    biome
    yarn
    nodejs

    # Misc Packages
    nerd-fonts.iosevka
    dconf
  ];
}