# Auto-generated by compose2nix.

{
  pkgs,
  lib,
  config,
  ...
}:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces =
    let
      matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
    in

    {
      "${matchAll}".allowedUDPPorts = [ 53 ];
    };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."browsertrix-crawler" = {
    image = "docker.io/webrecorder/browsertrix-crawler:latest";
    volumes = [
      "/home/yousuf/Downloads/crawls:/crawls:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cap-add=NET_ADMIN"
      "--cap-add=SYS_ADMIN"
      "--network-alias=crawler"
      "--network=browsertrix_default"
      "--shm-size=1073741824"
    ];
  };
  systemd.services."podman-browsertrix-crawler" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-browsertrix_default.service"
    ];
    requires = [
      "podman-network-browsertrix_default.service"
    ];
    partOf = [
      "podman-compose-browsertrix-root.target"
    ];
    wantedBy = [
      "podman-compose-browsertrix-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-browsertrix_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f browsertrix_default";
    };
    script = ''
      podman network inspect browsertrix_default || podman network create browsertrix_default
    '';
    partOf = [ "podman-compose-browsertrix-root.target" ];
    wantedBy = [ "podman-compose-browsertrix-root.target" ];
  };

  # Builds
  systemd.services."podman-build-browsertrix-crawler" = {
    path = [
      pkgs.podman
      pkgs.git
    ];
    serviceConfig = {
      Type = "oneshot";
      TimeoutSec = 300;
    };
    script = ''
      cd /home/yousuf/Downloads
      podman build -t webrecorder/browsertrix-crawler:latest .
    '';
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-browsertrix-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
