# Auto-generated by compose2nix.

{
  pkgs,
  lib,
  config,
  ...
}:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces =
    let
      matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
    in
    {
      "${matchAll}".allowedUDPPorts = [ 53 ];
    };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."sparkyfitness-db" = {
    image = "docker.io/postgres:18.3-alpine";
    environment = {
      "GUID" = "1000";
      "POSTGRES_DB" = "sparkyfitness_db";
      "POSTGRES_PASSWORD" = "changeme_db_password";
      "POSTGRES_USER" = "sparky";
      "PUID" = "1000";
    };
    environmentFiles = [
      "/home/yousuf/Downloads/sparkyfitness/.env"
    ];
    volumes = [
      "/home/yousuf/Downloads/sparkyfitness/postgresql:/var/lib/postgresql:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=sparkyfitness-db"
      "--network=sparkyfitness_sparkyfitness-network"
    ];
  };
  systemd.services."podman-sparkyfitness-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-sparkyfitness_sparkyfitness-network.service"
    ];
    requires = [
      "podman-network-sparkyfitness_sparkyfitness-network.service"
    ];
    partOf = [
      "podman-compose-sparkyfitness-root.target"
    ];
    wantedBy = [
      "podman-compose-sparkyfitness-root.target"
    ];
  };
  virtualisation.oci-containers.containers."sparkyfitness-sparkyfitness-frontend" = {
    image = "docker.io/codewithcj/sparkyfitness:latest";
    environment = {
      "GUID" = "1000";
      "NGINX_ACCESS_LOG" = "";
      "NGINX_DUMP_CONFIG" = "false";
      "NGINX_ERROR_LOG" = "";
      "NGINX_LISTEN_PORT" = "";
      "NGINX_RATE_LIMIT" = "5r/s";
      "PUID" = "1000";
      "SPARKY_FITNESS_FRONTEND_URL" = "http://localhost:3004";
      "SPARKY_FITNESS_SERVER_HOST" = "sparkyfitness-server";
      "SPARKY_FITNESS_SERVER_PORT" = "3010";
      "NODE_OPTIONS" = "--dns-result-order=ipv4first";
      "ALLOW_PRIVATE_NETWORK_CORS" = "false";
    };
    environmentFiles = [
      "/home/yousuf/Downloads/sparkyfitness/.env"
    ];
    ports = [
      "3004:80/tcp"
    ];
    dependsOn = [
      "sparkyfitness-sparkyfitness-server"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=sparkyfitness-frontend"
      "--network=sparkyfitness_sparkyfitness-network"
    ];
  };
  systemd.services."podman-sparkyfitness-sparkyfitness-frontend" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-sparkyfitness_sparkyfitness-network.service"
    ];
    requires = [
      "podman-network-sparkyfitness_sparkyfitness-network.service"
    ];
    partOf = [
      "podman-compose-sparkyfitness-root.target"
    ];
    wantedBy = [
      "podman-compose-sparkyfitness-root.target"
    ];
  };
  virtualisation.oci-containers.containers."sparkyfitness-sparkyfitness-server" = {
    image = "docker.io/codewithcj/sparkyfitness_server:latest";
    environment = {
      "ALLOW_PRIVATE_NETWORK_AI" = "false";
      "ALLOW_PRIVATE_NETWORK_CORS" = "false";
      "BETTER_AUTH_SECRET" = "changeme_replace_with_a_strong_better_auth_secret";
      "DEV_TOOLS_ENABLED" = "false";
      "GARMIN_MICROSERVICE_URL" = "http://sparkyfitness-garmin:8000";
      "GUID" = "1000";
      "HTTPS_PROXY" = "";
      "HTTP_PROXY" = "";
      "NODE_ENV" = "production";
      "NO_PROXY" = "";
      "PUID" = "1000";
      "SPARKY_FITNESS_ADMIN_EMAIL" = "";
      "SPARKY_FITNESS_API_ENCRYPTION_KEY" = "changeme_replace_with_a_64_character_hex_string";
      "SPARKY_FITNESS_API_KEY_RATELIMIT_MAX_REQUESTS" = "";
      "SPARKY_FITNESS_API_KEY_RATELIMIT_WINDOW_MS" = "";
      "SPARKY_FITNESS_APP_DB_PASSWORD" = "password";
      "SPARKY_FITNESS_APP_DB_USER" = "sparky_app";
      "SPARKY_FITNESS_CUSTOM_BACKUP_DIRECTORY" = "";
      "SPARKY_FITNESS_CUSTOM_UPLOADS_DIRECTORY" = "";
      "SPARKY_FITNESS_DB_HOST" = "sparkyfitness-db";
      "SPARKY_FITNESS_DB_NAME" = "sparkyfitness_db";
      "SPARKY_FITNESS_DB_PASSWORD" = "changeme_db_password";
      "SPARKY_FITNESS_DB_PORT" = "5432";
      "SPARKY_FITNESS_DB_USER" = "sparky";
      "SPARKY_FITNESS_DISABLE_EMAIL_LOGIN" = "";
      "SPARKY_FITNESS_DISABLE_SIGNUP" = "false";
      "SPARKY_FITNESS_EMAIL_FROM" = "";
      "SPARKY_FITNESS_EMAIL_HOST" = "";
      "SPARKY_FITNESS_EMAIL_PASS" = "";
      "SPARKY_FITNESS_EMAIL_PORT" = "";
      "SPARKY_FITNESS_EMAIL_SECURE" = "";
      "SPARKY_FITNESS_EMAIL_USER" = "";
      "SPARKY_FITNESS_EXTRA_TRUSTED_ORIGINS" = "";
      "SPARKY_FITNESS_FORCE_EMAIL_LOGIN" = "true";
      "SPARKY_FITNESS_FRONTEND_URL" = "http://localhost:3004";
      "SPARKY_FITNESS_LOG_LEVEL" = "ERROR";
      "SPARKY_FITNESS_OIDC_ADMIN_GROUP" = "";
      "SPARKY_FITNESS_OIDC_AUTH_ENABLED" = "";
      "SPARKY_FITNESS_OIDC_AUTO_REDIRECT" = "";
      "SPARKY_FITNESS_OIDC_AUTO_REGISTER" = "";
      "SPARKY_FITNESS_OIDC_CLIENT_ID" = "";
      "SPARKY_FITNESS_OIDC_CLIENT_SECRET" = "";
      "SPARKY_FITNESS_OIDC_DOMAIN" = "";
      "SPARKY_FITNESS_OIDC_ID_TOKEN_SIGNED_ALG" = "";
      "SPARKY_FITNESS_OIDC_ISSUER_URL" = "";
      "SPARKY_FITNESS_OIDC_LOGO_URL" = "";
      "SPARKY_FITNESS_OIDC_PROVIDER_NAME" = "";
      "SPARKY_FITNESS_OIDC_PROVIDER_SLUG" = "";
      "SPARKY_FITNESS_OIDC_SCOPE" = "";
      "SPARKY_FITNESS_OIDC_TIMEOUT" = "";
      "SPARKY_FITNESS_OIDC_TOKEN_AUTH_METHOD" = "";
      "SPARKY_FITNESS_OIDC_USERINFO_SIGNED_ALG" = "";
      "SPARKY_FITNESS_PUBLIC_API_DOCS" = "false";
      "TZ" = "Etc/UTC";
    };
    environmentFiles = [
      "/home/yousuf/Downloads/sparkyfitness/.env"
    ];
    volumes = [
      "/home/yousuf/Downloads/sparkyfitness/backup:/app/SparkyFitnessServer/backup:rw"
      "/home/yousuf/Downloads/sparkyfitness/uploads:/app/SparkyFitnessServer/uploads:rw"
    ];
    dependsOn = [
      "sparkyfitness-db"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=sparkyfitness-server"
      "--network=sparkyfitness_sparkyfitness-network"
    ];
  };
  systemd.services."podman-sparkyfitness-sparkyfitness-server" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-sparkyfitness_sparkyfitness-network.service"
    ];
    requires = [
      "podman-network-sparkyfitness_sparkyfitness-network.service"
    ];
    partOf = [
      "podman-compose-sparkyfitness-root.target"
    ];
    wantedBy = [
      "podman-compose-sparkyfitness-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-sparkyfitness_sparkyfitness-network" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f sparkyfitness_sparkyfitness-network";
    };
    script = ''
      podman network inspect sparkyfitness_sparkyfitness-network || podman network create sparkyfitness_sparkyfitness-network --driver=bridge
    '';
    partOf = [ "podman-compose-sparkyfitness-root.target" ];
    wantedBy = [ "podman-compose-sparkyfitness-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-sparkyfitness-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
