# Auto-generated by compose2nix.

{
  pkgs,
  lib,
  config,
  ...
}:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces =
    let
      matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
    in
    {
      "${matchAll}".allowedUDPPorts = [ 53 ];
    };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."yubal" = {
    image = "ghcr.io/guillevc/yubal:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "YUBAL_DOWNLOAD_UGC" = "false";
      "YUBAL_SCHEDULER_CRON" = "0 0 * * *";
      "YUBAL_TZ" = "UTC";
    };
    volumes = [
      "/home/yousuf/.local/share/yubal:/app/config:rw"
      "/home/yousuf/Music:/app/data:rw"
    ];
    ports = [
      "8000:8000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=yubal"
      "--network=yubal_default"
    ];
  };
  systemd.services."podman-yubal" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-yubal_default.service"
    ];
    requires = [
      "podman-network-yubal_default.service"
    ];
    partOf = [
      "podman-compose-yubal-root.target"
    ];
    wantedBy = [
      "podman-compose-yubal-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-yubal_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f yubal_default";
    };
    script = ''
      podman network inspect yubal_default || podman network create yubal_default
    '';
    partOf = [ "podman-compose-yubal-root.target" ];
    wantedBy = [ "podman-compose-yubal-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-yubal-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
