cd ~/Downloads/
new_tab
launch --title="yazi" fish -c "yazi && fish"
new_tab
launch --title="btm" fish -c "btm && fish"
new_tab
launch --title="nvim" fish -c "nvim ~/.local/share/chezmoi/dot_config/nvim/init.lua"
new_tab
