layerrules = true
kill_bind = "ctrl+shift+alt, h"

[launcher]
default_terminal = "kitty"
width = 650
max_items = 5
show_when_empty = true
animate_launch_ms = 250

[launcher.plugins.applications]
run_cache_weeks = 4
show_execs = true

[launcher.plugins.terminal]

[launcher.plugins.shell]

[launcher.plugins.websearch]
engines = []

[launcher.plugins.calc]

[windows]
scale = 8.5
workspaces_per_row = 5
trip_html_from_workspace_title = true

[windows.overview]
filter_by: [same_class]

# [windows.overview.open]
# key = "Tab"
# modifier = "ctrl"

[windows.overview.navigate]
forward = "tab"

[windows.overview.navigate.reverse]
key = "grave"

[windows.overview.other]
filter_by = []
hide_filtered = false

[windows.switch.open]
modifier = "ctrl"

[windows.switch.navigate]
forward = "tab"

[windows.switch.navigate.reverse]
key = "grave"

[windows.switch.other]
filter_by = []
hide_filtered = true
