# Misc settings
autofit=90%x90%
save-position-on-quit
keep-open=yes
resume-playback=yes
hr-seek = yes
osc=no
no-osd-bar

# Hardware & Quality Settings
vo=gpu-next,gpu
hwdec=auto
gpu-api=auto 
hwdec-codecs=all 

# Screenshot settings 
screenshot-format=png
screenshot-dir=~/Downloads/
screenshot-template="%F %p"


target-colorspace-hint=no 
